version: '3.9'

services:
  recipefy:
    container_name: recipefy
    image: vardanyanzaven/recipefy-mern:v1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./certs:/app/certs
    ports:
      - '8000:8000'
    