name: Recipefy CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci-cd:
    env:
      NODE_ENV: test
      CI: false
      PORT: 8000
      MONGO_DB_URL: mongodb://localhost/recipefy
      MONGO_DB_TEST_URL: mongodb://localhost/test
      JWT_SECRET: fakejwtsecret
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["6.0"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Use MongoDB version ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Add key and cert files
        run: |
          mkdir certs
          echo "${{ secrets.RECIPEFY_KEY }}" > certs/key.pem
          echo "${{ secrets.RECIPEFY_CERT }}" > certs/cert.pem
          echo "${{ secrets.RECIPEFY_KEY_PAIR }}" > recipefy-key-pair.pem && chmod 600 recipefy-key-pair.pem

      - name: Install all packages
        run: npm run install-all

      - name: Run unit tests
        run: npm test --prefix client

      - name: Run API tests
        run: npm test --prefix server

      - name: Run E2E tests
        run: npm run run-e2e

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: make build && docker push vardanyanzaven/recipefy-mern:v1

      - name: Deploy changes to AWS
        run: |
           ls
           ssh -o StrictHostKeyChecking=no -i recipefy-key-pair.pem ec2-user@ec2-13-53-200-29.eu-north-1.compute.amazonaws.com '
           cd recipefy-mern
           git fetch origin
           git reset --hard origin/main
           bash ./bash.sh "MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}" "MONGO_DB_TEST_URL=${{ secrets.MONGO_DB_TEST_URL }}" "JWT_SECRET=${{ secrets.JWT_SECRET }}" "SPOONACULAR_API_KEY=${{ secrets.SPOONACULAR_API_KEY }}"
           '
