name: Recipefy CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    env:
      MONGO_DB_URL: mongodb://localhost/recipefy
      MONGO_DB_TEST_URL: mongodb://localhost/test
      JWT_SECRET: fakejwtsecret
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["6.0"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Use MongoDB version ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Install all packages
        run: npm run install-all

      - name: Run unit tests
        run: npm run test-client

      - name: Run API tests
        run: npm run test-server

      - name: Run E2E tests
        run: npm run test-e2e
